### ISSUE TITLE
L'affichage

### ISSUE THREAD

**Issue by CasoratiWeierstrass** [CasoratiWeierstrass/Villes#1]
Affichez-moi ce csv en html et plus vite que ça

**Comment by TitouanM2i** [comment]
Pas ouf ce chef de projet.

**Comment by KKRG92** [comment]
Let's go

**Comment by KKRG92** [comment]
On avance mais l'affichage n'est pas très beau

**Comment by CasoratiWeierstrass** [comment]
Ok c'est du bon boulot les gars, mais prenez pas la confiance !
